local sort = require("sort")

local data = { 9, 5, 7, 2, 8, 1, 3, 4, 6 }

print("Choose sorting algorithm")
print('[B]ubble sort')
print('[I]nsertion sort')
print('[S]election sort')
print("")
io.write("Answer: ")
local algorithm = io.read()
print("------------------")
if algorithm == "B" or algorithm == "b" then
  print("Bubble sort")
  print("")
  print("unsorted")
  sort.show(data)
  sort.bubble(data)
  print("")
  print("sorted")
  sort.show(data)
elseif algorithm == "I" or algorithm == "i" then
  print("Insertion sort")
  print("")
  print("unsorted")
  sort.show(data)
  sort.insert(data)
  print("")
  print("sorted")
  sort.show(data)
elseif algorithm == "S" or algorithm == "s" then
  print("Selection sort")
  print("")
  print("unsorted")
  sort.show(data)
  sort.select(data)
  print("")
  print("sorted")
  sort.show(data)
end
